name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Try to build
        shell: cmake -P {0}
        run: |
          execute_process(
            COMMAND cmake
              -S .
              -B build/Debug
              -D CMAKE_BUILD_TYPE=Debug
            RESULT_VARIABLE cmake_result
          )

          if (NOT cmake_result EQUAL 0)
            message(FATAL_ERROR "Bad exit status")
          endif ()
          
          cmake --build build/Debug